### ISSUE TITLE
vimeo URLs replaced to http

### ISSUE THREAD

**Issue by Chosko** [andoulla/angular-video#4]
Is there any reason why Vimeo URLs are replaced to http? The won't work on servers that require https

**Comment by Chosko** [comment]
@andoulla my bad... I saw right now that this has been fixed with https://github.com/andoulla/angular-video/commit/cb41234eaf8debfe7212709b3fda0db4d9f8bb48 in master. Do you plan to release it?.

**Comment by andoulla** [comment]
@Chosko sorry for the delay it is released on npm now. When time permits will release it on bower too
